import SwiftUI
import FirebaseFirestore

// MARK: - Patient Billing View
struct PatientBillingView: View {
    @ObservedObject var session = UserSession.shared
    @State private var invoices: [HMSInvoice] = []
    @State private var unifiedPaidInvoices: [HMSInvoice] = []
    @State private var isLoading = true
    @State private var showPaymentSheet = false
    @State private var selectedInvoice: HMSInvoice?

    var pendingInvoices: [HMSInvoice] { invoices.filter { $0.status == .pending } }
    var paidInvoices:    [HMSInvoice] { unifiedPaidInvoices }

    var body: some View {
        ZStack {
            AppTheme.background.ignoresSafeArea()

            if isLoading {
                ProgressView()
                    .scaleEffect(1.5)
                    .tint(AppTheme.primary)
            } else if pendingInvoices.isEmpty {
                noPendingBillsState
            } else {
                ScrollView(showsIndicators: false) {
                    VStack(spacing: 24) {
                        sectionHeader("Pending Bills", color: .orange)
                        ForEach(pendingInvoices) { invoice in
                            InvoiceBillCard(invoice: invoice, onPay: {
                                selectedInvoice = invoice
                                showPaymentSheet = true
                            })
                        }
                    }
                    .padding(.horizontal, 20)
                    .padding(.vertical, 16)
                }
            }
        }
        .navigationTitle("Billing & Invoices")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            ToolbarItem(placement: .navigationBarTrailing) {
                NavigationLink(destination: PatientPaidBillsView(paidInvoices: paidInvoices)) {
                    Image(systemName: "doc.text")
                        .foregroundColor(AppTheme.primary)
                }
            }
        }
        .onAppear {
            Task { await fetchInvoices() }
        }
        // Razorpay Sheet — same pattern as BookAppointmentView
        .razorpaySheet(
            isPresented: $showPaymentSheet,
            options: buildPaymentOptions()
        ) { result in
            handlePaymentResult(result)
        }
    }

    // MARK: - Sub-views

    private var emptyState: some View {
        VStack(spacing: 20) {
            Spacer()
            ZStack {
                Circle()
                    .fill(AppTheme.primary.opacity(0.08))
                    .frame(width: 100, height: 100)
                Image(systemName: "creditcard")
                    .font(.system(size: 44))
                    .foregroundColor(AppTheme.primary.opacity(0.5))
            }
            Text("No Bills Found")
                .font(.system(size: 20, weight: .bold, design: .rounded))
                .foregroundColor(AppTheme.textPrimary)
            Text("Your hospital bills will appear here\nonce generated by admin.")
                .font(.system(size: 14, weight: .medium))
                .foregroundColor(AppTheme.textSecondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 40)
            Spacer()
        }
    }

    private var noPendingBillsState: some View {
        VStack(spacing: 20) {
            Spacer()
            Text("You have no pending bills to pay right now.")
                .font(.system(size: 14, weight: .medium))
                .foregroundColor(AppTheme.textSecondary)
                .multilineTextAlignment(.center)
            Spacer()
        }
    }

    @ViewBuilder
    private func sectionHeader(_ title: String, color: Color) -> some View {
        HStack {
            Circle()
                .fill(color)
                .frame(width: 8, height: 8)
            Text(title)
                .font(.system(size: 18, weight: .bold, design: .rounded))
                .foregroundColor(AppTheme.textPrimary)
            Spacer()
        }
    }

    // MARK: - Data Fetching
    private func fetchInvoices() async {
        guard let patientId = session.currentUser?.id else {
            await MainActor.run { isLoading = false }
            return
        }
        
        do {
            async let fetchInvoicesTask = InventoryRepository.shared.fetchInvoices(patientId: patientId)
            async let fetchPaidTask = InventoryRepository.shared.fetchUnifiedPaidTransactions(patientId: patientId)
            
            let (fetchedInvoices, unifiedPaid) = try await (fetchInvoicesTask, fetchPaidTask)
            
            await MainActor.run {
                self.invoices = fetchedInvoices
                self.unifiedPaidInvoices = unifiedPaid
                self.isLoading = false
            }
        } catch {
            #if DEBUG
            print("⚠️ fetchInvoices error: \(error)")
            #endif
            await MainActor.run { self.isLoading = false }
        }
    }

    // MARK: - Razorpay

    private func buildPaymentOptions() -> RazorpayOptions {
        guard let invoice = selectedInvoice,
              let user = session.currentUser else {
            return RazorpayOptions(amountInPaise: 100, description: "Medical Bill",
                                   prefillName: "", prefillEmail: "", prefillContact: "")
        }
        return RazorpayOptions(
            amountInPaise: max(100, Int(invoice.totalAmount * 100)),
            description:   "Medical Bill Payment",
            prefillName:   user.fullName,
            prefillEmail:  user.email,
            prefillContact: user.phoneNumber ?? ""
        )
    }

    private func handlePaymentResult(_ result: RazorpayPaymentResult) {
        guard let invoice = selectedInvoice else { return }
        if case .success(let paymentId) = result {
            #if DEBUG
            print("✅ Payment success: \(paymentId)")
            #endif
            Task {
                try? await InventoryRepository.shared.markInvoicePaid(id: invoice.firestoreId, razorpayPaymentId: paymentId)
                await fetchInvoices()
            }
        }
        selectedInvoice = nil
    }
}

// MARK: - Invoice Bill Card

struct InvoiceBillCard: View {
    let invoice: HMSInvoice
    var onPay: (() -> Void)? = nil
    var onViewPDF: (() -> Void)? = nil

    private var statusColor: Color { invoice.status == .paid ? .green : .orange }

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {

            // Header
            HStack {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Invoice #\(String(invoice.firestoreId.prefix(8)).uppercased())")
                        .font(.system(size: 13, weight: .semibold, design: .rounded))
                        .foregroundColor(AppTheme.textSecondary)
                    Text(invoice.date.formatted(date: .long, time: .omitted))
                        .font(.system(size: 15, weight: .bold, design: .rounded))
                        .foregroundColor(AppTheme.textPrimary)
                }
                Spacer()
                Text(invoice.status == .paid ? "Paid" : "Due")
                    .font(.system(size: 12, weight: .semibold))
                    .foregroundColor(statusColor)
                    .padding(.horizontal, 10)
                    .padding(.vertical, 4)
                    .background(statusColor.opacity(0.12))
                    .cornerRadius(8)
            }

            Divider()

            // Line items
            ForEach(invoice.items) { item in
                HStack {
                    Text("\(item.quantity)x \(item.name)")
                        .font(.system(size: 14))
                        .foregroundColor(AppTheme.textPrimary)
                    Spacer()
                    Text(String(format: "₹%.2f", item.amount))
                        .font(.system(size: 14, weight: .medium))
                        .foregroundColor(AppTheme.textSecondary)
                }
            }

            Divider()

            // Totals
            HStack {
                Text("Subtotal")
                    .font(.system(size: 13))
                    .foregroundColor(AppTheme.textSecondary)
                Spacer()
                Text(String(format: "₹%.2f", invoice.subTotal))
                    .font(.system(size: 13))
                    .foregroundColor(AppTheme.textSecondary)
            }
            HStack {
                Text("Tax (5%)")
                    .font(.system(size: 13))
                    .foregroundColor(AppTheme.textSecondary)
                Spacer()
                Text(String(format: "₹%.2f", invoice.tax))
                    .font(.system(size: 13))
                    .foregroundColor(AppTheme.textSecondary)
            }
            HStack {
                Text("Total Amount")
                    .font(.system(size: 16, weight: .bold, design: .rounded))
                    .foregroundColor(AppTheme.textPrimary)
                Spacer()
                Text(String(format: "₹%.2f", invoice.totalAmount))
                    .font(.system(size: 18, weight: .bold, design: .rounded))
                    .foregroundColor(AppTheme.primary)
            }

            // Action Button — show Pay Now for unpaid, View PDF for paid
            if invoice.status == .pending, let onPay = onPay {
                Button(action: onPay) {
                    HStack {
                        Image(systemName: "creditcard.fill")
                        Text("Pay Now")
                            .fontWeight(.bold)
                    }
                    .foregroundColor(.white)
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 14)
                    .background(
                        LinearGradient(
                            colors: [AppTheme.primary, AppTheme.primaryMid],
                            startPoint: .leading, endPoint: .trailing
                        )
                    )
                    .cornerRadius(14)
                    .shadow(color: AppTheme.primary.opacity(0.3), radius: 8, x: 0, y: 4)
                }
            } else if invoice.status == .paid, let onViewPDF = onViewPDF {
                Button(action: onViewPDF) {
                    HStack {
                        Image(systemName: "doc.text.fill")
                        Text("View / Download PDF")
                            .fontWeight(.bold)
                    }
                    .foregroundColor(AppTheme.primary)
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 14)
                    .background(AppTheme.primary.opacity(0.1))
                    .cornerRadius(14)
                }
            }
        }
        .padding(16)
        .background(AppTheme.cardSurface)
        .cornerRadius(18)
        .shadow(color: .black.opacity(0.05), radius: 10, x: 0, y: 4)
    }
}
