import SwiftUI
import FirebaseFirestore

// MARK: - Patient Billing View
struct PatientBillingView: View {
    @ObservedObject var session = UserSession.shared
    @State private var invoices: [Invoice] = []
    @State private var isLoading = true
    @State private var showPaymentSheet = false
    @State private var selectedInvoice: Invoice?

    var pendingInvoices: [Invoice] { invoices.filter { $0.status == "pending" } }
    var paidInvoices:    [Invoice] { invoices.filter { $0.status == "paid"    } }

    var body: some View {
        NavigationStack {
            ZStack {
                AppTheme.background.ignoresSafeArea()

                if isLoading {
                    ProgressView()
                        .scaleEffect(1.5)
                        .tint(AppTheme.primary)
                } else if invoices.isEmpty {
                    emptyState
                } else {
                    ScrollView(showsIndicators: false) {
                        VStack(spacing: 24) {
                            if !pendingInvoices.isEmpty {
                                sectionHeader("Pending Bills", color: .orange)
                                ForEach(pendingInvoices) { invoice in
                                    InvoiceBillCard(invoice: invoice) {
                                        selectedInvoice = invoice
                                        showPaymentSheet = true
                                    }
                                }
                            }
                            if !paidInvoices.isEmpty {
                                sectionHeader("Payment History", color: .green)
                                ForEach(paidInvoices) { invoice in
                                    InvoiceBillCard(invoice: invoice, onPay: nil)
                                }
                            }
                        }
                        .padding(.horizontal, 20)
                        .padding(.vertical, 16)
                    }
                }
            }
            .navigationTitle("Billing & Invoices")
            .navigationBarTitleDisplayMode(.inline)
            .onAppear {
                Task { await fetchInvoices() }
            }
            // Razorpay Sheet — same pattern as BookAppointmentView
            .razorpaySheet(
                isPresented: $showPaymentSheet,
                options: buildPaymentOptions()
            ) { result in
                handlePaymentResult(result)
            }
        }
    }

    // MARK: - Sub-views

    private var emptyState: some View {
        VStack(spacing: 20) {
            Spacer()
            ZStack {
                Circle()
                    .fill(AppTheme.primary.opacity(0.08))
                    .frame(width: 100, height: 100)
                Image(systemName: "creditcard")
                    .font(.system(size: 44))
                    .foregroundColor(AppTheme.primary.opacity(0.5))
            }
            Text("No Bills Found")
                .font(.system(size: 20, weight: .bold, design: .rounded))
                .foregroundColor(AppTheme.textPrimary)
            Text("Your hospital bills will appear here\nonce generated by admin.")
                .font(.system(size: 14, weight: .medium))
                .foregroundColor(AppTheme.textSecondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 40)
            Spacer()
        }
    }

    @ViewBuilder
    private func sectionHeader(_ title: String, color: Color) -> some View {
        HStack {
            Circle()
                .fill(color)
                .frame(width: 8, height: 8)
            Text(title)
                .font(.system(size: 18, weight: .bold, design: .rounded))
                .foregroundColor(AppTheme.textPrimary)
            Spacer()
        }
    }

    // MARK: - Data Fetching — Inline (same pattern as PatientLabRequestsView)

    private func fetchInvoices() async {
        guard let patientId = session.currentUser?.id else {
            await MainActor.run { isLoading = false }
            return
        }
        let db = Firestore.firestore()
        do {
            let snapshot = try await db.collection("invoices")
                .whereField("patientId", isEqualTo: patientId)
                .getDocuments()

            let fetched: [Invoice] = snapshot.documents.compactMap { doc in
                let d = doc.data()
                guard
                    let patientId   = d["patientId"]   as? String,
                    let patientName = d["patientName"] as? String,
                    let subTotal    = d["subTotal"]    as? Double,
                    let tax         = d["tax"]         as? Double,
                    let totalAmount = d["totalAmount"] as? Double,
                    let status      = d["status"]      as? String,
                    let dateTS      = d["date"]        as? Timestamp
                else { return nil }

                let rawItems = d["items"] as? [[String: Any]] ?? []
                let items: [InvoiceItem] = rawItems.compactMap { item in
                    guard let name = item["name"] as? String,
                          let amount = item["amount"] as? Double else { return nil }
                    return InvoiceItem(id: item["id"] as? String ?? UUID().uuidString,
                                       name: name, amount: amount)
                }

                return Invoice(
                    id:          doc.documentID,
                    patientId:   patientId,
                    patientName: patientName,
                    items:       items,
                    subTotal:    subTotal,
                    tax:         tax,
                    totalAmount: totalAmount,
                    status:      status,
                    date:        dateTS.dateValue(),
                    paymentDate: (d["paymentDate"] as? Timestamp)?.dateValue(),
                    pdfUrl:      d["pdfUrl"] as? String,
                    generatedBy: d["generatedBy"] as? String ?? ""
                )
            }
            .sorted { $0.date > $1.date }

            await MainActor.run {
                self.invoices = fetched
                self.isLoading = false
            }
        } catch {
            print("⚠️ fetchInvoices error: \(error)")
            await MainActor.run { self.isLoading = false }
        }
    }

    // MARK: - Razorpay — same pattern as BookAppointmentView

    private func buildPaymentOptions() -> RazorpayOptions {
        guard let invoice = selectedInvoice,
              let user = session.currentUser else {
            return RazorpayOptions(amountInPaise: 100, description: "Medical Bill",
                                   prefillName: "", prefillEmail: "", prefillContact: "")
        }
        return RazorpayOptions(
            amountInPaise: max(100, Int(invoice.totalAmount * 100)),
            description:   "Medical Bill Payment",
            prefillName:   user.fullName,
            prefillEmail:  user.email,
            prefillContact: user.phoneNumber ?? ""
        )
    }

    private func handlePaymentResult(_ result: RazorpayPaymentResult) {
        guard let invoice = selectedInvoice else { return }
        if case .success(let paymentId) = result {
            print("✅ Payment success: \(paymentId)")
            Task {
                let db = Firestore.firestore()
                try? await db.collection("invoices").document(invoice.id).updateData([
                    "status": "paid",
                    "paymentDate": Timestamp(date: Date())
                ])
                await fetchInvoices()
            }
        }
        selectedInvoice = nil
    }
}

// MARK: - Invoice Bill Card

struct InvoiceBillCard: View {
    let invoice: Invoice
    var onPay: (() -> Void)?

    private var statusColor: Color { invoice.status == "paid" ? .green : .orange }

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {

            // Header
            HStack {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Invoice #\(String(invoice.id.prefix(8)).uppercased())")
                        .font(.system(size: 13, weight: .semibold, design: .rounded))
                        .foregroundColor(AppTheme.textSecondary)
                    Text(invoice.date.formatted(date: .long, time: .omitted))
                        .font(.system(size: 15, weight: .bold, design: .rounded))
                        .foregroundColor(AppTheme.textPrimary)
                }
                Spacer()
                Text(invoice.status == "paid" ? "Paid" : "Due")
                    .font(.system(size: 12, weight: .semibold))
                    .foregroundColor(statusColor)
                    .padding(.horizontal, 10)
                    .padding(.vertical, 4)
                    .background(statusColor.opacity(0.12))
                    .cornerRadius(8)
            }

            Divider()

            // Line items
            ForEach(invoice.items) { item in
                HStack {
                    Text(item.name)
                        .font(.system(size: 14))
                        .foregroundColor(AppTheme.textPrimary)
                    Spacer()
                    Text(String(format: "₹%.2f", item.amount))
                        .font(.system(size: 14, weight: .medium))
                        .foregroundColor(AppTheme.textSecondary)
                }
            }

            Divider()

            // Totals
            HStack {
                Text("Subtotal")
                    .font(.system(size: 13))
                    .foregroundColor(AppTheme.textSecondary)
                Spacer()
                Text(String(format: "₹%.2f", invoice.subTotal))
                    .font(.system(size: 13))
                    .foregroundColor(AppTheme.textSecondary)
            }
            HStack {
                Text("Tax (5%)")
                    .font(.system(size: 13))
                    .foregroundColor(AppTheme.textSecondary)
                Spacer()
                Text(String(format: "₹%.2f", invoice.tax))
                    .font(.system(size: 13))
                    .foregroundColor(AppTheme.textSecondary)
            }
            HStack {
                Text("Total Amount")
                    .font(.system(size: 16, weight: .bold, design: .rounded))
                    .foregroundColor(AppTheme.textPrimary)
                Spacer()
                Text(String(format: "₹%.2f", invoice.totalAmount))
                    .font(.system(size: 18, weight: .bold, design: .rounded))
                    .foregroundColor(AppTheme.primary)
            }

            // Action Button
            if let onPay = onPay {
                Button(action: onPay) {
                    HStack {
                        Image(systemName: "creditcard.fill")
                        Text("Pay Now")
                            .fontWeight(.bold)
                    }
                    .foregroundColor(.white)
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 14)
                    .background(
                        LinearGradient(
                            colors: [AppTheme.primary, AppTheme.primaryMid],
                            startPoint: .leading, endPoint: .trailing
                        )
                    )
                    .cornerRadius(14)
                    .shadow(color: AppTheme.primary.opacity(0.3), radius: 8, x: 0, y: 4)
                }
            } else {
                // Download / View invoice PDF
                Button(action: {
                    if let urlStr = invoice.pdfUrl, let url = URL(string: urlStr) {
                        UIApplication.shared.open(url)
                    }
                }) {
                    HStack {
                        Image(systemName: "arrow.down.doc.fill")
                        Text("Download Invoice")
                            .fontWeight(.semibold)
                    }
                    .font(.system(size: 14))
                    .foregroundColor(AppTheme.primary)
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 12)
                    .background(AppTheme.primaryLight.opacity(0.3))
                    .cornerRadius(12)
                    .overlay(
                        RoundedRectangle(cornerRadius: 12)
                            .stroke(AppTheme.primary.opacity(0.4), lineWidth: 1)
                    )
                }
                .disabled(invoice.pdfUrl == nil)
                .opacity(invoice.pdfUrl != nil ? 1 : 0.5)
            }
        }
        .padding(16)
        .background(AppTheme.cardSurface)
        .cornerRadius(18)
        .shadow(color: .black.opacity(0.05), radius: 10, x: 0, y: 4)
    }
}

// MARK: - Models (co-located, same pattern as PatientLabRequestsView)

struct Invoice: Identifiable {
    let id: String
    let patientId: String
    let patientName: String
    let items: [InvoiceItem]
    let subTotal: Double
    let tax: Double
    let totalAmount: Double
    let status: String      // "pending" | "paid"
    let date: Date
    let paymentDate: Date?
    let pdfUrl: String?
    let generatedBy: String
}

struct InvoiceItem: Identifiable {
    let id: String
    let name: String
    let amount: Double
}
